# Assignment 06

### For Questions refer [README](https://github.com/DSAghicha/LU-AI-ML/blob/main/Day_14_15/README.md)

In [1]:
import numpy as np

## Question 1

In [2]:
print("3x3x3 Array:")
print(np.random.rand(3, 3, 3))

3x3x3 Array:
[[[0.02312287 0.31690617 0.83350168]
  [0.94745766 0.95186147 0.36231842]
  [0.25099009 0.45191524 0.83127992]]

 [[0.26731617 0.61729208 0.1225446 ]
  [0.12763776 0.54354718 0.40665795]
  [0.78575899 0.61181512 0.24606757]]

 [[0.8209315  0.67355406 0.96275882]
  [0.72997445 0.24813563 0.77493944]
  [0.96604354 0.26690764 0.99241153]]]


## Question 2

In [3]:
print("Required matrix is:")
print(np.diag([1,2,3,4], k = -1))

Required matrix is:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Question 3

In [4]:
def checkboard_pattern(n:int) -> list:
    """
    Returns matrix in checkboard pattern for the provided size.
    Black is represented as '1'
    White is represented as '2'
    Parameters:
        n (int): Size of the Board.
    Returns:
        board (list): List of 0, 1 in checkboard pattern.
    Raises:
        TypeError if n is not an integer.
    """
    if not type(n) is int:
        raise TypeError("Board Size must be an integer!")
    board: list = []
    for i in range(n):
        if i % 2 == 0:
            board.append(list(np.tile([0, 1], int(n/2))))
        else:
            board.append(list(np.tile([1,0], int(n/2))))
    return board


In [5]:
print("8x8 matrix in checkboard pattern is:")
checkboard_pattern(8)

8x8 matrix in checkboard pattern is:


[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

## Question 4

In [6]:
an_array = np.random.rand(5,5)
norm = np.linalg.norm(an_array)
print(an_array, "\nis normalised to\n", an_array / norm)

[[0.95059281 0.85980107 0.45209374 0.89622149 0.93483327]
 [0.395384   0.24240373 0.07582887 0.62706438 0.44923671]
 [0.70459164 0.60839883 0.01644481 0.2571736  0.08058998]
 [0.64597052 0.86963451 0.43309941 0.22545099 0.09619433]
 [0.76748611 0.98875282 0.76397492 0.98167545 0.7410699 ]] 
is normalised to
 [[0.29527557 0.26707361 0.14043052 0.27838661 0.2903803 ]
 [0.12281519 0.07529607 0.02355416 0.19478034 0.13954306]
 [0.21886206 0.1889824  0.00510813 0.07988392 0.02503307]
 [0.20065302 0.2701281  0.13453045 0.07003017 0.02988013]
 [0.2383985  0.30712893 0.23730784 0.30493054 0.23019303]]


## Question 5

In [7]:
def common_val(arr1, arr2):
    return np.intersect1d(arr1, arr2)


In [8]:
arr1 = [0, 10, 20, 40, 60]
arr2 = [10, 30, 20]
print(f"Common values in {arr1} & {arr2} is { common_val(arr1, arr2)}")

Common values in [0, 10, 20, 40, 60] & [10, 30, 20] is [10 20]


## Question 6

In [9]:
import datetime


today = datetime.date.today()
one = datetime.timedelta(days=1)

print("Today is:", today.strftime("%d-%m-%Y"))
print("Yesterday was:", (today - one).strftime("%d-%m-%Y"))
print("Tomorrow will be:", (today + one).strftime("%d-%m-%Y"))


Today is: 26-06-2021
Yesterday was: 25-06-2021
Tomorrow will be: 27-06-2021


## Question 7

In [10]:
arr1 = np.random.rand(2,2)
arr2 = np.random.rand(2,2)
if np.array_equal(arr1, arr2):
    print (arr1, "\n==\n", arr2)
else:
    print(arr1, "\n!=\n", arr2)

[[0.79908813 0.78826349]
 [0.77621615 0.40469198]] 
!=
 [[0.22853519 0.93037382]
 [0.72312219 0.13495272]]


## Question 8

In [11]:
vector = np.random.random(10)
print("Vector is:", vector)

vmax = vector.max()
print("Maximum value is:", vmax)

vector[vector.argmax()] = 0

print("Revised vector is:", vector)

Vector is: [0.33978032 0.11569839 0.68184544 0.65303493 0.99642486 0.51857829
 0.09710229 0.12516252 0.03693943 0.72314824]
Maximum value is: 0.9964248552293469
Revised vector is: [0.33978032 0.11569839 0.68184544 0.65303493 0.         0.51857829
 0.09710229 0.12516252 0.03693943 0.72314824]


## Question 9

In [12]:
arr = np.random.random(20)
np.set_printoptions(threshold=np.inf)
print(arr)

[0.25395345 0.89071168 0.01631228 0.94276291 0.23829473 0.94174778
 0.55402426 0.31692647 0.5397035  0.61877337 0.9532497  0.35147154
 0.24002864 0.78073488 0.65504566 0.82640899 0.53509142 0.19481595
 0.01705869 0.94077686]


## Question 10

In [13]:
arr = np.random.rand(3, 2)
print("Original Array is\n", arr)
print("Array after subtracting each row by its mean is:\n", arr - arr.mean(axis=1, keepdims=True))

Original Array is
 [[0.12870166 0.77202932]
 [0.48167653 0.71084489]
 [0.26184914 0.2061139 ]]
Array after subtracting each row by its mean is:
 [[-0.32166383  0.32166383]
 [-0.11458418  0.11458418]
 [ 0.02786762 -0.02786762]]


# Question 11

In [14]:
arr = np.random.randint(10, size=10)
one_arr = np.ones(10)
one_arr += np.bincount(arr)
print(one_arr)

[4. 2. 1. 1. 1. 2. 1. 4. 2. 2.]


## Question 12

In [15]:
arr1 = np.random.rand(2,2)
arr2 = np.random.rand(2,2)
arr_dot = np.dot(arr1, arr2)

print(f"Array A:\n{arr1}\nArray B:\n{arr2}")
print("Their Dot Product:\n", arr_dot)
print("Its diagonal is:", np.diag(arr_dot))

Array A:
[[0.60414332 0.22039772]
 [0.61051119 0.8769523 ]]
Array B:
[[0.92826986 0.56489622]
 [0.05438117 0.95497851]]
Their Dot Product:
 [[0.57279352 0.55175337]
 [0.61440883 1.18234608]]
Its diagonal is: [0.57279352 1.18234608]


## Question 13

In [16]:
arr = np.random.randint(10, size= 20)
freq_val = np.bincount(arr).argmax()
print("Array is:", arr)
print("Most Frequent value(s):", freq_val)
print("Number of occurence(s):", np.count_nonzero(arr== freq_val))

Array is: [6 3 3 9 9 5 1 7 9 3 5 2 8 6 9 5 0 2 9 5]
Most Frequent value(s): 9
Number of occurence(s): 5


## Question 14

In [17]:
def largest_val(arr, count):
    """
    Returns array of n largest values
    Parameters:
        arr (ndarray): Primary Array
        count (int): Number of values required
    Returns:
        arr (1darray): Array of n largest values.
    """
    sorted_arr = arr[np.argsort(arr)]

    return sorted_arr[-count:]

In [18]:
arr = np.random.randint(10000, size= 20)
count = 5
print(f"{count} largest values of {arr} are {(largest_val(arr, count))}")

5 largest values of [8376 8122 3680 3163 3435 3839 7998 5286 9072 6426 8152 1739 1468 5108
 4361 9572 7599 5596 5671 5269] are [8122 8152 8376 9072 9572]


## Question 15

In [19]:
arr = np.random.rand(2,4)
rec_arr = np.rec.array(arr)
print(f"Regular Array: {type(arr)}\n{arr}")
print(f"Record Array: {type(rec_arr)}\n{rec_arr}")

Regular Array: <class 'numpy.ndarray'>
[[0.93672867 0.91698832 0.06765651 0.74428766]
 [0.61381611 0.46348167 0.34270945 0.91643554]]
Record Array: <class 'numpy.recarray'>
[[0.93672867 0.91698832 0.06765651 0.74428766]
 [0.61381611 0.46348167 0.34270945 0.91643554]]
