# Assignment 14-15

### For Questions refer [README](https://github.com/DSAghicha/LU-AI-ML/blob/main/Day_14_15/README.md)

In [1]:
import numpy as np

## Question 1

In [2]:
print("3x3x3 Array:")
print(np.random.rand(3, 3, 3))

3x3x3 Array:
[[[0.29877528 0.40116043 0.52022592]
  [0.7977934  0.44545402 0.13108539]
  [0.63081546 0.27429006 0.56005728]]

 [[0.92309824 0.40290379 0.50648665]
  [0.71576241 0.44575146 0.81532602]
  [0.89166425 0.11591158 0.47468811]]

 [[0.25276391 0.99178876 0.44501389]
  [0.38455469 0.82480168 0.70538534]
  [0.05212343 0.86537914 0.19455704]]]


## Question 2

In [3]:
print("Required matrix is:")
print(np.diag([1,2,3,4], k = -1))

Required matrix is:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Question 3

In [4]:
def checkboard_pattern(n:int) -> list:
    """
    Returns matrix in checkboard pattern for the provided size.
    Black is represented as '1'
    White is represented as '0'
    Parameters:
        n (int): Size of the Board.
    Returns:
        board (list): List of 0, 1 in checkboard pattern.
    Raises:
        TypeError if n is not an integer.
    """
    if not type(n) is int:
        raise TypeError("Board Size must be an integer!")
    board: list = []
    for i in range(n):
        if i % 2 == 0:
            board.append(list(np.tile([0, 1], int(n/2))))
        else:
            board.append(list(np.tile([1,0], int(n/2))))
    return board


In [5]:
print("8x8 matrix in checkboard pattern is:")
checkboard_pattern(8)

8x8 matrix in checkboard pattern is:


[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

## Question 4

In [6]:
an_array = np.random.rand(5,5)
norm = np.linalg.norm(an_array)
print(an_array, "\nis normalised to\n", an_array / norm)

[[0.14458288 0.0544317  0.61732233 0.14326998 0.44004541]
 [0.32360761 0.29348325 0.74508068 0.44226839 0.29727925]
 [0.25344552 0.87961044 0.66024484 0.4262512  0.39363694]
 [0.76893877 0.36741479 0.09132652 0.3605073  0.05532379]
 [0.00108785 0.59283635 0.96394606 0.53071494 0.83304552]] 
is normalised to
 [[0.05722518 0.0215438  0.24433311 0.05670554 0.17416778]
 [0.12808228 0.11615921 0.29489923 0.17504763 0.11766165]
 [0.10031248 0.34814544 0.26132162 0.1687081  0.15579954]
 [0.30434214 0.14542095 0.03614658 0.14268699 0.02189688]
 [0.00043057 0.23464168 0.38152505 0.21005433 0.32971527]]


## Question 5

In [7]:
def common_val(arr1, arr2):
    return np.intersect1d(arr1, arr2)


In [8]:
arr1 = [0, 10, 20, 40, 60]
arr2 = [10, 30, 20]
print(f"Common values in {arr1} & {arr2} is { common_val(arr1, arr2)}")

Common values in [0, 10, 20, 40, 60] & [10, 30, 20] is [10 20]


## Question 6

In [9]:
import datetime


today = datetime.date.today()
one = datetime.timedelta(days=1)

print("Today is:", today.strftime("%d-%m-%Y"))
print("Yesterday was:", (today - one).strftime("%d-%m-%Y"))
print("Tomorrow will be:", (today + one).strftime("%d-%m-%Y"))


Today is: 26-06-2021
Yesterday was: 25-06-2021
Tomorrow will be: 27-06-2021


## Question 7

In [10]:
arr1 = np.random.rand(2,2)
arr2 = np.random.rand(2,2)
if np.array_equal(arr1, arr2):
    print (arr1, "\n==\n", arr2)
else:
    print(arr1, "\n!=\n", arr2)

[[0.50815088 0.90763155]
 [0.6914485  0.29197157]] 
!=
 [[0.23488256 0.03005815]
 [0.05287262 0.0535312 ]]


## Question 8

In [11]:
vector = np.random.random(10)
print("Vector is:", vector)

vmax = vector.max()
print("Maximum value is:", vmax)

vector[vector.argmax()] = 0

print("Revised vector is:", vector)

Vector is: [0.65966243 0.41039519 0.90832133 0.73682862 0.36983286 0.33494025
 0.43345716 0.90064695 0.13621604 0.41592413]
Maximum value is: 0.9083213262581227
Revised vector is: [0.65966243 0.41039519 0.         0.73682862 0.36983286 0.33494025
 0.43345716 0.90064695 0.13621604 0.41592413]


## Question 9

In [12]:
arr = np.random.random(20)
np.set_printoptions(threshold=np.inf)
print(arr)

[0.4751773  0.45308792 0.27967273 0.86017075 0.03224136 0.78706278
 0.55975372 0.17829588 0.49104312 0.65249344 0.92315312 0.5386876
 0.35713295 0.42804093 0.03654276 0.14226405 0.79037056 0.97445073
 0.6798679  0.70888104]


## Question 10

In [13]:
arr = np.random.rand(3, 2)
print("Original Array is\n", arr)
print("Array after subtracting each row by its mean is:\n", arr - arr.mean(axis=1, keepdims=True))

Original Array is
 [[0.72995822 0.18510617]
 [0.7819348  0.70711961]
 [0.91429956 0.84061199]]
Array after subtracting each row by its mean is:
 [[ 0.27242603 -0.27242603]
 [ 0.0374076  -0.0374076 ]
 [ 0.03684379 -0.03684379]]


# Question 11

In [14]:
arr = np.random.randint(10, size=10)
one_arr = np.ones(10)
one_arr += np.bincount(arr)
print(one_arr)

[2. 3. 1. 2. 1. 1. 4. 2. 1. 3.]


## Question 12

In [15]:
arr1 = np.random.rand(2,2)
arr2 = np.random.rand(2,2)
arr_dot = np.dot(arr1, arr2)

print(f"Array A:\n{arr1}\nArray B:\n{arr2}")
print("Their Dot Product:\n", arr_dot)
print("Its diagonal is:", np.diag(arr_dot))

Array A:
[[0.97946337 0.75661806]
 [0.7618353  0.73696886]]
Array B:
[[0.59884417 0.28384758]
 [0.63538761 0.32079702]]
Their Dot Product:
 [[1.06729167 0.52073912]
 [0.92448151 0.45266252]]
Its diagonal is: [1.06729167 0.45266252]


## Question 13

In [16]:
arr = np.random.randint(10, size= 20)
freq_val = np.bincount(arr).argmax()
print("Array is:", arr)
print("Most Frequent value(s):", freq_val)
print("Number of occurence(s):", np.count_nonzero(arr== freq_val))

Array is: [6 8 8 6 4 3 3 8 0 9 0 3 2 5 1 4 3 0 5 0]
Most Frequent value(s): 0
Number of occurence(s): 4


## Question 14

In [17]:
def largest_val(arr, count):
    """
    Returns array of n largest values
    Parameters:
        arr (ndarray): Primary Array
        count (int): Number of values required
    Returns:
        arr (1darray): Array of n largest values.
    """
    sorted_arr = arr[np.argsort(arr)]

    return sorted_arr[-count:]

In [18]:
arr = np.random.randint(10000, size= 20)
count = 5
print(f"{count} largest values of {arr} are {(largest_val(arr, count))}")

5 largest values of [3613  742  375 6083 1549 8948 3270 7778 3668 5085 1875  851 2669 8242
 5618 1408 7019 7190 2620 6349] are [7019 7190 7778 8242 8948]


## Question 15

In [19]:
arr = np.random.rand(2,4)
rec_arr = np.rec.array(arr)
print(f"Regular Array: {type(arr)}\n{arr}")
print(f"Record Array: {type(rec_arr)}\n{rec_arr}")

Regular Array: <class 'numpy.ndarray'>
[[0.53546537 0.67933706 0.43335985 0.89153642]
 [0.74195561 0.00145305 0.57057966 0.16034165]]
Record Array: <class 'numpy.recarray'>
[[0.53546537 0.67933706 0.43335985 0.89153642]
 [0.74195561 0.00145305 0.57057966 0.16034165]]
